# This is the base configuration file.
# Properties defined here are common to all profiles or serve as a default.

# Default Logging Configuration
logging:
  level:
    root: WARN
    com.nanogate: INFO

# Spring Boot Configuration
spring:
  application:
    name: NanoGate
  threads:
    virtual:
      enabled: true

# Actuator Configuration
management:
  endpoints:
    web:
      base-path: /actuator # Set the base path for actuator endpoints
      exposure:
        include: "*" # Expose all actuator endpoints over HTTP (e.g., /actuator/health, /actuator/metrics)
  endpoint:
    health:
      show-details: always # Always show full health details, not just "UP" or "DOWN"
  health:
    redis:
      enabled: false # Disable Redis health check for now, as Redis is not running locally

# NanoGate Core Configuration
nanogate:
  routing:
    enabled: true
    # Global Default HTTP Client Configuration
    default-http-client:
      connectTimeout: 5s
      responseTimeout: 15s
    # Global Default Resilience (Circuit Breaker) Configuration
    default-resilience:
      failureRateThreshold: 50.0
      slowCallRateThreshold: 100.0
      slowCallDurationThreshold: 10s
      permittedNumberOfCallsInHalfOpenState: 10
      slidingWindowSize: 100
      waitDurationInOpenState: 30s
    # Global Default Health Check Configuration
    default-health-check:
      path: /health
      interval: 10s
      timeout: 2s
